name: Run grumphp with different versions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['kanti/buildy:7.3', 'kanti/buildy:7.4', 'kanti/buildy:8.0']
        composer:
          - install --no-progress --no-scripts -n
          - require phpro/grumphp:* --no-progress --no-scripts -n
          - update --no-progress --no-scripts -n --prefer-lowest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - run: composer ${{ matrix.composer }}
      - run: ./vendor/bin/grumphp run
